# Generated by Django 5.2.14 on 2026-05-18 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
