# Generated by Django 5.2.14 on 2026-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraincome',
            name='budget_category_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
