# Generated by Django 5.2.14 on 2026-06-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_extraincome_budget_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_base_rate', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default='1.50', max_digits=4)),
                ('estimated_tax_rate', models.DecimalField(decimal_places=2, default='0.25', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Overtime Settings',
            },
        ),
    ]
