# Generated by Django 5.2.14 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
